# Site settings
title: AngelKevin Blog
SEOTitle: AngelKevin的博客 | AK Blog
header-img: img/mine/mmexport1603726804966.jpg
email: kaiwenz531@gmail.com (kevin)
email: 2816475252@qq.com (angel)
description: "If you want the crown then you've got to break them down."
keyword: "AngelKevin, AngelKevin Blog, 凯文的博客, 张凯文,周浩 ,zkw,AK的博客"
url: "http://angelkevin.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/angelkevin/angelkevin.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "永远相信美好的事情即将发生"
sidebar-avatar: /img/touxiang.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     no using
#zhihu_username:     no using
#github_username:    no using
#facebook_username:  No using
#jianshu_username:   No using
#twitter_username:   No using




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
#disqus_username: zkw22154

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 219f880627084895bd31                           #生成的clientID
  clientSecret: 302609261010aaee9807af402c19865d4f282dbc   #生成的clientSecret
  repo: angelkevin.github.io    #仓库名称
  owner: angelkevin    #github用户名
  admin: angelkevin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Github",
        href: "https://github.com/angelkevin"
    },{
        title: "QQ",
        href: "https://user.qzone.qq.com/2215408861"
    }
]
